### PR TITLE
Dcokerfile adduser command

### PR DESCRIPTION
**Pull request by vibraniumSwaleh**
The `adduser` command in the Dockerfile fails on my Windows 11 system. I changed it to `useradd` and the installation was completed successfully. 

image

### CODE REVIEW

**Comment by streetdogg** [comment]
@vibraniumSwaleh Looks like many files are modified as part of the PR. I suppose it may have to do with the File Permissions change (since you were on Windows). I added a fix as part of this commit - https://github.com/inpyjama/c-ninja-listings/commit/22e0dfa0d47741c3db35e82087d780dc8228dc79

Can you check if this resolves the issue? If not, can I request you to clean up the PR and resubmit?

**Comment by vibraniumSwaleh** [comment]
@streetdogg That fixed it. I installed it again with the changes you made, and it worked. Thanks for your attention to this.

**Comment by vibraniumSwaleh** [comment]
@streetdogg I'll close this then. 

Thanks.

**Comment by streetdogg** [comment]
thanks for confirming, @vibraniumSwaleh! :)

**Pull request closed without merging**
